#########################################################################
# Title:         Sandbox: Settings | Main 2                             #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Sandbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Settings | Copy"
  ansible.builtin.include_tasks: "subtasks/copy.yml"
  vars:
    file: "{{ outer_item }}"

- name: "Settings | Decrypt"
  ansible.builtin.include_tasks: "subtasks/decrypt.yml"
  vars:
    file: "{{ outer_item }}"
  when: (outer_item != "ansible.cfg")

- name: "Settings | Migrator"
  ansible.builtin.include_tasks: "subtasks/migrator.yml"
  vars:
    file: "{{ outer_item }}"

- name: "Settings | Updater"
  ansible.builtin.include_tasks: "subtasks/updater.yml"
  vars:
    file: "{{ outer_item }}"
  when: (outer_item != "ansible.cfg")

- name: "Settings | Re-encrypt"
  ansible.builtin.include_tasks: "subtasks/reencrypt.yml"
  vars:
    file: "{{ outer_item }}"
  when: (outer_item != "ansible.cfg")
